### ISSUE TITLE
Find a new project name and harmonize terms

### ISSUE THREAD

**Issue by otetard** [roundbroker/roundbroker#21]
This is not a real “issue” but more a space to discuss the new project name. Feel free to make name propositions here.

We also need to harmonize terms and URL all around the code. For example, we have “pivot”, “sub”/“pub”, “consume”/“produce”, “pull”/“push”, “publish”, etc.

From my perspective, I don’t think we should use the “sub”/“pub” terms, as they directly refer to the way Nchan works (and it may be possible that at some point we replace that solution). I prefer the terms “push“/“pull”.

To be continued.

**Comment by restanrm** [comment]
I think that 'pivot' is a good name. also 'pusher' and 'puller' could stay there. 

For the project name, 'webPivot' could be used. But we also have to find a name for the client and server programs.

**Comment by restanrm** [comment]
Following an oral discussion. Several thematic can be used: 
- transport
  - goods
    - water
    - electricitiy
    - objects
  - people
    - train
    - boat
    - plane
  - informations
    - through nerves (body, etc.)

**Comment by gbossert** [comment]
the following domain name has been bought and redirected to our IP:
roundbroker.io.
We need to define the syntax of our service: 
* Roundbroker, 
* roundbroker, 
* Round Broker, 
* Round broker

**Comment by restanrm** [comment]
I like "RoundBroker" or "Roundbroker" because "roundbroker" seems flat.

**Comment by gbossert** [comment]
I like your 'db' thing, for the mirror of course which we will make sure to leverages in the coming soon logo. Given that my favorite brand name would be "roundbroker".

**Comment by restanrm** [comment]
Ok, sold it. It seems a little flat, but it's the easiest in every aspect.
